Repository ArmaForces/Website, pull requests merged in 2020-01, with the labels that each got.

#34 Feature/improved roles check
  .env
  README.md
  config/services.yaml
  src/Exception/MissingConfigParameterValueException.php
  src/Security/DiscordAuthenticator.php
  src/Security/Exception/MultipleRolesFound.php
  src/Security/Exception/RequiredRolesNotAssignedException.php
Labels: enhancement

#36 Fix controller actions names
  src/Controller/HomeController.php
  src/Controller/SecurityController.php
Labels: cleanup

#38 Improvements for SEO
  public/favicon.ico
  public/img/ArmaForces.png
  public/img/favicon-192x192.png
  public/img/logo.svg
  templates/_partial/_navbar.html.twig
  templates/base.html.twig
  templates/home/index/_partial/pl/_about_us.html.twig
  templates/home/index/index.html.twig
  templates/home/join_us/join_us.html.twig
  translations/messages.pl.yaml
Labels: enhancement

#37 Fix logo text scaling on mobiles
  assets/app.scss
  templates/home/index/index.html.twig
Labels: bugfix

#39 Add auto deployment of prod from master branch
  .github/workflows/docker.yml
Labels: feature

#42 Add mission archive image lazy load
  assets/app.js
  assets/app.scss
  package-lock.json
  package.json
  public/img/placeholder_320x250.png
  templates/home/missions/missions.html.twig
Labels: enhancement

#43 Add google analytics support
  .env
  config/packages/twig.yaml
  templates/base.html.twig
Labels: feature

#46 Fixes for mobile layouts
  assets/app.scss
  assets/landing.scss
  templates/home/index/_partial/_missions.html.twig
Labels: bugfix

#47 Resize images via imgproxy/imgproxy
  .env
  config/services.yaml
  docker-compose.override.yml
  src/Twig/ImgproxyExtension.php
  templates/home/index/_partial/_missions.html.twig
  templates/home/missions/missions.html.twig
Labels: feature

#49 Update imgproxy settings
  docker-compose.override.yml
Labels: enhancement

#51 Center mission title, add number of enlisted players
  src/Service/Mission/Dto/MissionDto.php
  templates/home/index/_partial/_missions.html.twig
  templates/home/missions/missions.html.twig
  translations/messages.pl.yaml
Labels: enhancement

#52 Feature/permissions
  assets/app.scss
  config/doctrine/Permissions.Permissions.orm.xml
  config/doctrine/User.UserEntity.orm.xml
  config/packages/security.yaml
  config/packages/twig.yaml
  src/Command/PermissionsMakeAdminCommand.php
  src/Controller/UserController.php
  src/Entity/Permissions/Permissions.php
  src/Entity/User/AbstractUserEntity.php
  src/Entity/User/UserEntity.php
  src/Form/User/UserPermissionsType.php
  src/Migrations/Version20200123221244.php
  src/Repository/PermissionsRepository.php
  src/Repository/UserEntityRepository.php
  src/Security/DiscordAuthenticator.php
  src/Security/Enum/PermissionsEnum.php
  src/Security/Voter/User/DeleteUsersVoter.php
  src/Security/Voter/User/ListUsersVoter.php
  src/Security/Voter/User/ManageUsersPermissionsVoter.php
  templates/_partial/_navbar.html.twig
  templates/user/list.html.twig
  templates/user/permissions.html.twig
  translations/messages.pl.yaml
Labels: feature

#55 Reverse display order of open missions
  templates/home/missions/missions.html.twig
Labels: enhancement

#57 Feature/cs fixer config improvement
  .php_cs.dist
  src/Security/DiscordAuthenticator.php
  src/Service/Mission/Dto/MissionDto.php
  src/Service/Mission/MissionClient.php
Labels: cleanup

#56 Make PermissionsMakeAdminCommand interactive
  src/Command/PermissionsMakeAdminCommand.php
Labels: enhancement

#61 Feature/calendar links
  .docker/Dockerfile
  assets/app.scss
  composer.json
  composer.lock
  src/Service/Mission/Dto/MissionDto.php
  src/Twig/CalendarExtension.php
  symfony.lock
  templates/_partial/_mission_widget.html.twig
  templates/home/index/_partial/_missions.html.twig
  templates/home/missions/missions.html.twig
Labels: feature

#64 Adjust time range of calendar event links from -30m to +2h
  src/Twig/CalendarExtension.php
Labels: enhancement

#67 Restore image lazy loading on missions page
  templates/_partial/_mission_widget.html.twig
  templates/home/missions/missions.html.twig
Labels: bugfix
