Repository ArmaForces/Website, pull requests merged in 2021-02, with the labels that each got.

#170 Feature/dropmenu improvements
  templates/_partial/_mission_widget.html.twig
  templates/_partial/_navbar.html.twig
  templates/mod_list_public/customize.html.twig
Labels: enhancement

#174 Move navbar to separate partial
  templates/_partial/_navbar.html.twig
  templates/_partial/navbar/_navbar.html.twig
  templates/_partial/navbar/_navbar_icons.html.twig
  templates/_partial/navbar/_navbar_links.html.twig
  templates/default.html.twig
  templates/home/index/index.html.twig
  translations/messages.pl.yaml
Labels: enhancement

#176 CI Improvements
  .github/workflows/application.yml
  .github/workflows/tests.yml
Labels: cleanup, ignore changelog

#178 Feature/en translation
  config/packages/translation.yaml
  src/EventSubscriber/UserLocaleRequestSubscriber.php
  templates/_partial/mod_group_tabs/_mod_group_tabs_table.html.twig
  templates/_partial/mod_tabs/_mod_tabs_table.html.twig
  templates/base.html.twig
  templates/home/index/_partial/_about.html.twig
  templates/home/index/_partial/_missions.html.twig
  templates/home/join_us/_partial/pl/join_steps.html.twig
  templates/home/join_us/join_us.html.twig
  templates/mod_list_public/_partial/_optional_mods_tab.html.twig
  templates/user_group/_partial/_users_table.html.twig
  translations/messages.pl.yaml
Labels: enhancement

#183 1.10.1
  src/Controller/ModListPublicController.php
Labels: ignore changelog

#184 Add mod list download tests
  src/DataFixtures/Mod/Optional/AceInteractionMenuExpansionModFixture.php
  src/DataFixtures/Mod/Required/ArmaForcesModsModFixture.php
  src/DataFixtures/Mod/Required/Broken/ArmaForcesAceMedicalModFixture.php
  src/DataFixtures/Mod/Required/Deprecated/LegacyArmaForcesModsModFixture.php
  src/DataFixtures/Mod/Required/Disabled/ArmaForcesJbadBuildingFixModFixture.php
  src/DataFixtures/ModList/DefaultModListFixture.php
  src/Test/Enum/RouteEnum.php
  src/Test/Traits/AssertsTrait.php
  src/Test/Traits/DataProvidersTrait.php
  tests/functional/Api/Controller/ModList/GetModListByNameActionTest.php
  tests/functional/Api/Controller/ModList/GetModListsByIdActionTest.php
  tests/functional/Controller/ModListPublicController/DownloadActionTest.php
Labels: cleanup

#186 Improve templates readability
  templates/_partial/navbar/_navbar_icons.html.twig
  templates/_partial/navbar/_navbar_links.html.twig
  templates/home/join_us/_partial/pl/join_steps.html.twig
  templates/home/missions/missions.html.twig
Labels: cleanup

#188 Fix/group permissions
  src/Form/Mod/ModFormType.php
  src/Form/ModList/DataTransformer/ModListFormDtoDataTransformer.php
  src/Form/ModList/ModListFormType.php
  src/Security/Voter/AbstractVoter.php
Labels: bugfix

#185 Discord authenticator refactor
  config/services.yaml
  src/Security/DiscordAuthenticator.php
Labels: cleanup
