Repository ArmaForces/Website, pull requests merged in 2021-08, with the labels that each got.

#223 Increase GC time for sessions
  config/packages/framework.yaml
Labels: bugfix

#224 Release 1.13.0
  Makefile
  config/doctrine/Dlc/Dlc.orm.xml
  config/doctrine/ModGroup/ModGroup.orm.xml
  config/doctrine/ModList/ModList.orm.xml
  config/packages/framework.yaml
  migrations/Version20210625211018.php
  migrations/Version20210627001232.php
  public/img/error/403.webp
  public/img/error/404.webp
  public/img/error/500.webp
  src/Api/DataTransformer/DlcOutputDataTransformer.php
  src/Api/Dto/DlcOutput.php
  src/Command/PermissionsMakeAdminCommand.php
  src/Controller/ModController.php
  src/Controller/ModGroupController.php
  src/Entity/Dlc/Dlc.php
  src/Entity/Dlc/DlcInterface.php
  src/Form/Dlc/DataTransformer/DlcFormDtoDataTransformer.php
  src/Form/Dlc/DlcFormType.php
  src/Form/Dlc/Dto/DlcFormDto.php
  src/Form/Mod/Dto/ModFormDto.php
  src/Validator/Dlc/UniqueDirectoryDlc.php
  src/Validator/Dlc/UniqueDirectoryDlcValidator.php
  src/Validator/WindowsDirectoryName.php
  src/Validator/WindowsDirectoryNameValidator.php
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  translations/messages.pl.yaml
  translations/validators.pl.yaml
Labels: ignore changelog

#226 Feature/attendance
  .env
  .env.test
  config/api_platform/resources.yaml
  config/doctrine/Attendance/Attendance.orm.xml
  config/packages/doctrine.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20210827203818.php
  src/Api/DataTransformer/Attendance/AttendanceInputDataTransformer.php
  src/Api/DataTransformer/Attendance/AttendanceOutputDataTransformer.php
  src/Api/DataTransformer/Dlc/DlcOutputDataTransformer.php
  src/Api/DataTransformer/Mod/ModOutputDataTransformer.php
  src/Api/DataTransformer/ModList/ModListDetailsOutputDataTransformer.php
  src/Api/DataTransformer/ModList/ModListOutputDataTransformer.php
  src/Api/Input/Attendance/AttendanceInput.php
  src/Api/Output/Attendance/AttendanceOutput.php
  src/Api/Output/Dlc/DlcOutput.php
  src/Api/Output/Mod/ModOutput.php
  src/Api/Output/ModList/ModListDetailsOutput.php
  src/Api/Output/ModList/ModListOutput.php
  src/DataFixtures/Attendance/AttendanceFixtures.php
  src/Doctrine/Dbal/Types/BigIntType.php
  src/Entity/Attendance/Attendance.php
  src/Entity/Attendance/AttendanceInterface.php
  src/Entity/Mod/SteamWorkshopMod.php
  src/Entity/User/User.php
  src/Repository/Attendance/AttendanceRepository.php
  src/Security/Authenticator/ApiKeyAuthenticator.php
  src/Security/Model/ApiTokenUser.php
  src/Security/Traits/UserInterfaceTrait.php
  src/Test/Enum/RouteEnum.php
  src/Validator/AbstractValidator.php
  src/Validator/Attendance/UniqueAttendance.php
  src/Validator/Attendance/UniqueAttendanceValidator.php
  src/Validator/Dlc/UniqueDirectoryDlcValidator.php
  src/Validator/Dlc/UniqueSteamStoreDlcValidator.php
  src/Validator/Mod/UniqueDirectoryModValidator.php
  src/Validator/Mod/UniqueSteamWorkshopModValidator.php
  src/Validator/ModGroup/UniqueModGroupNameValidator.php
  src/Validator/ModList/UniqueModListNameValidator.php
  src/Validator/SteamProfileId.php
  src/Validator/SteamProfileIdValidator.php
  src/Validator/UserGroup/UniqueUserGroupNameValidator.php
  tests/functional/Api/Controller/Attendance/CreateAttendanceActionTest.php
  tests/functional/Api/Controller/ModList/GetModListByNameActionTest.php
  tests/functional/Api/Controller/ModList/GetModListsActionTest.php
  tests/functional/Api/Controller/ModList/GetModListsByIdActionTest.php
  translations/validators.pl.yaml
Labels: feature

#227 Feature/edit user profile
  config/doctrine/Permissions/User/UserManagementPermissions.orm.xml
  config/doctrine/User/User.orm.xml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20210827225825.php
  src/Command/PermissionsMakeAdminCommand.php
  src/Controller/ModGroupController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/Entity/Permissions/AbstractPermissions.php
  src/Entity/Permissions/User/UserManagementPermissions.php
  src/Entity/User/User.php
  src/Entity/User/UserInterface.php
  src/Form/Permissions/User/UserManagementPermissionsType.php
  src/Form/User/DataTransformer/UserFormDtoDataTransformer.php
  src/Form/User/Dto/UserFormDto.php
  src/Form/User/UserFormType.php
  src/Security/Authenticator/DiscordAuthenticator.php
  src/Security/Enum/ConnectionsEnum.php
  src/Security/Enum/PermissionsEnum.php
  src/Security/Enum/ScopeEnum.php
  src/Security/Voter/User/UpdateUserVoter.php
  src/Service/RestCord/DiscordClientFactory.php
  src/Service/RestCord/Enum/TokenTypeEnum.php
  src/Service/Steam/Helper/SteamHelper.php
  src/Test/Enum/RouteEnum.php
  src/Twig/SteamExtension.php
  src/Validator/User/UniqueUserSteamId.php
  src/Validator/User/UniqueUserSteamIdValidator.php
  templates/user/form.html.twig
  templates/user/list.html.twig
  templates/user_group/form.html.twig
  tests/functional/Api/Controller/ModList/GetModListByNameActionTest.php
  tests/functional/Api/Controller/ModList/GetModListsActionTest.php
  tests/functional/Api/Controller/ModList/GetModListsByIdActionTest.php
  tests/functional/Controller/UserController/UpdateActionTest.php
  tests/unit/Service/RestCord/DiscordClientFactoryTest.php
  translations/messages.pl.yaml
  translations/validators.pl.yaml
Labels: feature

#228 Update Symfony to the latest version
  .docker/Dockerfile
  .gitignore
  .php-cs-fixer.dist.php
  Makefile
  composer.json
  composer.lock
  docker-compose.test.yml
  phpstan.neon.dist
  symfony.lock
  tests/integration/Service/Steam/SteamApiClientTest.php
  tests/integration/Version/VersionProviderTest.php
  tests/unit/EventSubscriber/Doctrine/EntityBlamableSubscriberTest.php
  tests/unit/Service/RestCord/DiscordClientFactoryTest.php
  tests/unit/Service/Serializer/CircularReferenceHandlerTest.php
  tests/unit/Service/Steam/Helper/SteamHelperTest.php
  tests/unit/Service/Steam/SteamApiClientTest.php
Labels: enhancement

#231 Add authentication to api docs page
  config/packages/api_platform.yaml
Labels: documentation
