Repository ArmaForces/Website, pull requests merged in 2021-06, with the labels that each got.

#209 Remove invalid meta tag
  templates/mod_list_public/launcher_preset_template.html.twig
Labels: bugfix

#213 Release 1.12.2
  templates/mod_list/list.html.twig
  templates/mod_list_public/select.html.twig
Labels: enhancement

#214 Add CSLA CDLC icon
  public/img/dlc_icon/1294440.png
Labels: enhancement

#215 Release 1.12.2
  public/img/dlc_icon/1294440.png
Labels: ignore changelog
